### ISSUE TITLE
Requests not being Rate Limited Correctly - Add Percision

### ISSUE THREAD

**Issue by adrnola** [dudleycarr/ratelimit.js#14]
Hi Guys - 

Great node limiting library. 

I have noticed the following "bug"/observation.

For example:

``` javascript
interval = 180 Seconds (3 mins), 
limit = 15
```

1st request = 11:33:08.529 and the client has sent 9 of the 15 requests in the 1st 3 minute window at 11:33:51. With the 10th request being received at 11:34:27.514. 
We have noticed that if the next request is received at the end of the 1st 3 minute window + 1100 mill-seconds (or rather the last completed 3 minute window). Instead the requests being counted as 10, the limit counter has been re-set to 1.

What this means is that an attacker has more of an opportunity to issue more requests, instead of being limited to 6 requests, they are now free to issue 15 new requests. 

From looking at the sourcecode, you have: 
ratelimit.js\lua\check_limit.lua which appears to have code to address this, that is, line #7:

``` javascript
    local precision = limit[3] or duration
```

but it is never used as ratelimit.js\lib\rate_limit.js line #38 convertRules() function does not provide for using it:

``` javascript
 RateLimit.prototype.convertRules = function(rules) {
    var rule, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = rules.length; _i < _len; _i++) {
      rule = rules[_i];
      _results.push([rule.interval, rule.limit]);
    }
    return _results;
  };
```

Here are the results from our Redis investigations with our own test script redis_hgetall.js (I haven't printed out all Redis log entries and I changed our IP Address to XXX.XXX.X.XXX just in case you are wondering):

``` javascript
INFORMATION
2015-09-18T11:33:08.529Z
redis_hgetall.js HGETALL rl_app_01:XXX.XXX.X.XXX: Succeeded with result: { '1:1:o': '1442575983',
  '1:1:': '1',
  '180:180:o': '8014311',
  '180:180:': '1',
  '1:1:1442575983': '1',
  '180:180:8014311': '1' }

INFORMATION
2015-09-18T11:33:51.078Z
redis_hgetall.js HGETALL rl_app_01:XXX.XXX.X.XXX: Succeeded with result: { '1:1:o': '1442576026',
  '1:1:': '1',
  '180:180:o': '8014311',
  '180:180:': '9',
  '180:180:8014311': '9',
  '1:1:1442576026': '1' }

INFORMATION
2015-09-18T11:34:27.514Z
redis_hgetall.js HGETALL rl_app_01:XXX.XXX.X.XXX: Succeeded with result: { '1:1:o': '1442576067',
  '1:1:': '1',
  '1:1:1442576067': '1',
  '180:180:o': '8014311',
  '180:180:': '1',
  '180:180:8014311': '1' }

INFORMATION
2015-09-18T11:34:29.531Z
redis_hgetall.js HGETALL rl_app_01:XXX.XXX.X.XXX: Succeeded with result: { '1:1:o': '1442576067',
  '1:1:': '2',
  '1:1:1442576067': '2',
  '180:180:o': '8014311',
  '180:180:': '2',
  '180:180:8014311': '2' }
```

**So my question is: Are you planning on implementing the "precision" in the rate limiting rules for the next release of ratelimit.js ? And if so when do you think this will this be released ?**

This would solve the issue described above as ratelimit.js\lua\check_limit.lua line #7:

```
local precision = limit[3] or duration
precision = math.min(precision, duration)

local blocks = math.ceil(duration / precision)
local saved = {}

table.insert(saved_keys, saved)
saved.block_id = math.floor(now / precision)
saved.trim_before = saved.block_id - blocks + 1
saved.count_key = duration .. ':' .. precision .. ':'
saved.ts_key = saved.count_key .. 'o'
```

_This would mean the rate limit check is done in "precision" time rather than "duration" time._

We are using ratelimit.js v1.6.0

I hope my analysis is clear. If not just let me know.

Thanks.

Regards,
Adrian.

**Comment by adrnola** [comment]
Hi Dudley ( @dudleycarr ) /Josh (@joshgummersall) -

Just wondering if you have any feedback on the issue above ?

Thanks.

Regards,
Adrian.

**Comment by joshgummersall** [comment]
@adrnola looks like a really simple fix - just add the `precision` property to the rules. I've already got a quick fix for this that I'll submit a PR for.

**Comment by joshgummersall** [comment]
@adrnola can you grab the branch reference in the pull request [here](https://github.com/dudleycarr/ratelimit.js/issues/21) and let me know if that fixes your problem? You will have to modify your rules to add `precision`.
