### ISSUE TITLE
Is Redis a dependency? 

### ISSUE THREAD

**Issue by ScheerMT** [dudleycarr/ratelimit.js#16]
I am using ioredis instead of node_redis and came across a "module not found" for redis. Is the require statement for redis [Here](https://github.com/dudleycarr/ratelimit.js/blob/master/src/rate_limit.coffee#L5) necessary? I did a quick ctrl+F for redis in that file and only see references to the redisclient passed in by the constructor..

**Comment by ScheerMT** [comment]
I actually took that line out in my compiled .js file in my project and it appears to be fully working..

**Comment by joshgummersall** [comment]
Yeah - looks to be unused in that file. Thanks for the thorough reviews through the library! Feel free to submit PRs with fixes if you'd like, otherwise I'll get to this stuff as soon as I can.

**Comment by joshgummersall** [comment]
Fixed in 1.6.1 release. Thanks @ScheerMT!
