### ISSUE TITLE
Outdated Website

### ISSUE THREAD

**Issue by ScheerMT** [dudleycarr/ratelimit.js#22]
The [Website](http://ratelimit.io/) appears to be a bit dated as far as new features and changes are concerned. The chanelog there reflects changes up to 1.2 only whereas we are 1.6+ now. I couldn't find the site repo on your profile to try and help out. Is it private or not hosted on github? 

I really like this library and think it should have more exposure since the other rate limiting libraries aren't as feature rich nor use sliding windows!

**Comment by dudleycarr** [comment]
Would you mind doing a PR?

**Comment by ScheerMT** [comment]
I will get working on it. I'm still learning the details of github and gh-pages is new to me :)

**Comment by ScheerMT** [comment]
Was the site generated from markdown or just straight HTML?

**Comment by dudleycarr** [comment]
Sorry, I misunderstood what you were asking for originally. There is a manual process for the owner of the repo to have the Github page republished based on the latest version of the README. I just updated that so it's now updated. Thanks for pointing that out!

**Comment by ScheerMT** [comment]
Thanks for updating! I just came across that process myself, cool stuff.
