### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by peebles** [dudleycarr/ratelimit.js#23]
I do not understand "multiple rules per instance" and what that really means.  I do not understand "multiple instances of ratelimit for different categories of users".  I do not understand the "weight" extraction function.

I have a REST service with authenticated accounts.  Each account should have their own limits based on what paid tier they are in.  I think I could use extractIps to return an account id instead of an IP address.   But how to have a different rate limiter per account?

(An account might have multiple users, coming from different IP addresses.  The account is rate limited not users).

**Comment by joshgummersall** [comment]
There are two ways to accomplish this. The first:
- Use a middleware function to fetch a User object that has the information you need to determine rate limits (i.e. the User ID and tier)
- Use a custom `extractIps` function that returns the User ID
- Use a custom `weight` function that inspects the tier and determines how "expensive" the request is

If you had tiers like:
1. Ultra Pro Tier (unlimited requests)
2. Pro Tier
3. Free Tier

The following would work:

``` javascript
// Note: this should be set by a middleware function.
req.user = {
  id: 98765,
  tier: 0 // could be 1 or 2 as well
};

function extractIps (req) {
  return [req.user.id];
}

function weight (req) {
  switch req.user.tier;
}
```

The second would be using several different instances of a `RateLimit` object with different rules and each with a different prefix. In that case, you would construct an "ultraPro" rate limiter, a "pro" rate limiter, and a "free" rate limiter and then use a middleware function to decide which of those instances to use. Something like this should work:

``` javascript
var ultraProLimiter = new RateLimit(redisClient, ultraProRules, {prefix: 'ultraPro'});
var proLimiter = ...
var freeLimiter = ...

var middlewareOpts = {
  ...
};

var limitedRequest = function (req, res, next) {
  res.status(429).json({message: 'rate limit exceeded'});
}

var tieredLimiters = [
  new ExpressMiddleware(ultraProLimiter, middlewareOpts).middleware(limitedRequest),
  new ExpressMiddleware(proLimiter, middlewareOpts).middleware(limitedRequest),
  new ExpressMiddleware(freeLimiter, middlewareOpts).middleware(limitedRequest)
];

// Again, set by middleware
req.user = {
  id: 98765,
  tier: 2
};

app.use(function (req, res, next) {
  tieredLimiters[req.user.tier].middleware(req, res, next);
});
```

Quick note - I didn't test that code above, but with some minor fixes it should work.

**Comment by peebles** [comment]
Great!  I'll use those hints.  Seems like it'll do what I need.
a

**Comment by peebles** [comment]
I like the three tier idea.  If I set up the (one) limiter with say,
interval: 1, rate: 5, then how does "weight" of 0, 1 and 2 affect the rate
of "5 requests per second"?

Hm.  Is that the reason for an array of rules for a limiter?  Does the
weight just correspond to the index into that rules array?

I definitely understand the second example, but the first ...?

a

**Comment by joshgummersall** [comment]
The weight notion is a bit more complex - when you say `{interval: 1, rate: 5}` that means that a given thing (IP, user ID, etc) can register _events_ that sum to 5 (but no higher) for each interval. If you use the default configuration, the weight for each _event_ (request) is 1. If you use a custom weight function, the weight for each event is determined by the return value of that function.

So, if you were to use the "tier" as the weight, a tier of 0 would yield unlimited requests, a tier of 1 would yield whatever rate rules you specify, and a tier of 2 would _halve_ the rate rules you've specified (because each request counts for double).

The array of rules is meant more to specify different intervals, i.e. 10 requests/second, 100 requests/minute, 200 requests/day.

**Comment by peebles** [comment]
Ok, I see.  For the rules array, are the units of limit always specified in
seconds?
a

**Comment by joshgummersall** [comment]
Yes - the intervals are specified in seconds.

**Comment by peebles** [comment]
Ok, I'm humming along.  By looking at the code, I think the answer to this
next question is probably no, but I wonder if its possible to get some
status from a particular instance of a rate limiter.  There is another
library called "limitr" that returns these headers when a limit has been
exceeded:
- X-RateLimit-Limit- the maximum number of requests that the consumer is
  permitted to make within the rate window.
- X-RateLimit-Remaining- the number of requests remaining in the current
  rate limit window.
- X-RateLimit-Reset- the time at which the current rate limit window
  resets in UTC epoch milliseconds.

Something like that could be useful.

a

**Comment by joshgummersall** [comment]
There's another issue, namely https://github.com/dudleycarr/ratelimit.js/issues/13 that is requesting the same functionality. The sliding window functionality in this library makes that bit less than trivial given that windows can be of arbitrary length.

We opted to support multiple rules per limiter so you could feasibly make a single request and be well under a 5-minute sliding window limit, but make two more and exceed a 1-hour sliding window limit so the information returned in the headers would have to include information with regard to each window specified in the configuration. For the use case that @dudleycarr and I wanted to support originally this functionality was not a requirement.

You are more than welcome to investigate this and submit patches though! It's something that I think would be useful, I simply don't have the time to work on that at the moment.

**Comment by peebles** [comment]
Ok don't sweat it. Thanks a lot of all your help. 
A

**Comment by joshgummersall** [comment]
No problem - I'm going to go ahead and close this out as the rate-limit headers request is still open. Feel free to ping me here on this issue if anything else comes up.
