### ISSUE TITLE
Q: Giving Different Users Different Limits

### ISSUE THREAD

**Issue by juddflamm** [dudleycarr/ratelimit.js#28]
I want to use your module.  I also need to give different user accounts on my system different rate limits.  How would I do this with this module?  I was thinking about adding another attribute to your options object like this:

function getUserSpecificRateLimits(req) {
  return req.user.rateLimits;
}

var options = {
  rateLimits: getUserSpecificRateLimits,
  extractIps: extractIps,
  weight: weight
};

What do you think of this?  Or is there a better way?

Thank you!

**Comment by joshgummersall** [comment]
The `extractIps` functionality is named in a slightly confusing way that I plan to address. You should think of it more as an `extractIdentifiers` function. With that being said, here's how I would accomplish what you are trying to do:

``` js
/*
Assuming req.user looks like: {
  id: 'some_id',
  type: 'paid'
}
*/
var extractIps = function (req) {
  return [req.user.id];
}

var paidLimiter = new RateLimit(...);
var paidLimitMiddleware = new ExpressMiddleware(paidLimiter);
var freeLimiter = new RateLimit(...);
var freeLimitMiddleware = new ExpressMiddleware(freeLimiter);

var limiterMiddleware = function (req, res, next) {
  if (req.user.type === 'paid') {
    paidLimitMiddleware(req, res, next);
  } else {
    freeLimitMiddleware(req, res, next);
  }
}
```

Tying specific rate limits to a particular user is not quite as easy. For this library to function properly each separate set of rate limit rules needs to be associated with a separate RateLimiter instance.

**Comment by joshgummersall** [comment]
Going to close this out as the proposed solution should work.
