### ISSUE TITLE
Question about callback

### ISSUE THREAD

**Issue by cirrus-up-cloud** [dudleycarr/ratelimit.js#37]
I have a very stupid question about your first example:

var showRateLimited = function(err, isRateLimited) {
  if (err) {
    return console.log("Error: " + err);
  }

  console.log("Is rate limited? " + isRateLimited);
};

I have the following code

app.get("/account", function (req, res) {

    limiter.incr(req.query.username, 2, showRateLimited);

    return res.status(200).send(accountMock);
});

How can I use isRateLimited to actually return 429 and not only to print an error message on console?

**Comment by joshgummersall** [comment]
Take a look at the docs here: https://github.com/dudleycarr/ratelimit.js#express-middleware-usage

**Comment by cirrus-up-cloud** [comment]
I can't use that because I use restify.

**Comment by joshgummersall** [comment]
According to http://restify.com/docs/home/ it looks like you can use universal pre-handlers or universal handlers in the exact same way as Express middleware. Also, the route registration functions (`server.get`, `server.post`, etc.) accept a chain of Express middleware-compatible functions as well. Should be fully compatible.

**Comment by joshgummersall** [comment]
Going to go ahead and close this out. Feel free to re-open if you have other questions.
