### ISSUE TITLE
Seems awesome, but is it still in active development?

### ISSUE THREAD

**Issue by medmin** [dudleycarr/ratelimit.js#38]
Hi, guys, I am trying to develop a free and public service via api. I am trying to set some rate limit to my APIs. Your repo seems awesome.

But I couldn't help noticing that it's been 2 years since the last commit. So, is this repo still in active development? Thanks.

**Comment by joshgummersall** [comment]
Hey @medmin! Thanks for your interest.

At the moment there are no bugs or other major issues that are outstanding. With that in mind, the project should work as promised. We are not planning on adding new features at the moment though.

If you are looking for alternatives [Kong](https://getkong.org) seems promising when paired with the [Rate Limiter](https://getkong.org/plugins/rate-limiting/) plugin. This would decouple your service implementation from the general request handling pipeline that Kong implements.

**Comment by medmin** [comment]
Thanks.
